CREATE TABLE IF NOT EXISTS people (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    initials TEXT NOT NULL UNIQUE
);

ALTER TABLE completions ADD COLUMN person_id INTEGER REFERENCES people(id) ON DELETE SET NULL;
